---

# ansible-playbook playbook.yml

- hosts: webapp
  become: yes
  vars:
    ssh_users:
      - wfarrell
    ssh_sudo_users:
      - wfarrell
  roles:
    - update
    - galaxy.cis
  #  - galaxy.fail2ban
    - galaxy.sshd
    - galaxy.docker
  #  - galaxy.firewall
